#####################################
# Config File for Redwood           #
#                                   #
# This Config file is written using #
# the YAML language, please use     #
# appropiate syntax                 #
#####################################

clean: True         # Write a new logfile?
empty: True         # Flag empty directories?
and: False          # Flag if both conditions are met
delete: False       # Delete flagged files?
force: False        # Force delete?
logfile: ./log.txt  # File to write the log to
trash:              # What directory to use as a trash file
ignorefile: ./.redwood.ignore

directory_list:
    a:
        - directory: /home/sherlock/Projects/redwood/redwood/redwood_testing/level0
        - mindepth: 0
        - maxdepth: 3
        - age: 1d
        - reverse: False
